import encrypt_functions as e
from os import system
import os
#If your on a Windows computer set this to True
windows = False

def press_continue():
    input("Press ENTER to continue...")
    if windows:
        system('cls')
    else:
        system('clear')

def menu():
    print("")
    print("#######################")
    print("# Encrypt and Decrypt #")
    print("#######################")
    print("")
    print(" 1) Encrypt Message      d1) Decrypt Message")
    print(" 2) Encrypt Document     d2) Decrypt Document")
    print(" 3) Encrypt Image        d3) Decrypt Image")
    print(" 4) Encrypt Folders      d4) Decrypt Folders")
    print("")
    print(" 0) Create new key")
    print("")
    print(" q) Quit")
    print("")

def main_functions():
    while True:
        if windows:
            system('cls')
        else:
            system('clear')
        menu()
        PEIN = input(" --> ")
        print("")
        if PEIN == "1":
            print("What is the message?")
            msg = input(" --> ")
            print("")
            print("Where is your key located?")
            key = input(" --> ")
            print("")
            print('##############################')
            print("")
            e.encrypt_msg(msg, key)
            print("")
            print('##############################')
            press_continue()
        elif PEIN == 'q':
            if windows:
                system('cls')
            else:
                system('clear')
            break
        elif PEIN == 'd1':
            print("What is the encrypted message?")
            msg = input(" --> ")
            print("")
            print("Where is your key located?")
            key = input(" --> ")
            print("")
            print('##############################')
            print("")
            e.decrypt_msg(msg, key)
            print("")
            print('##############################')
            press_continue()
        elif PEIN == '2':
            print("Where is the Document located?")
            msg = input(" --> ")
            print("")
            print("Where is your key located?")
            key = input(" --> ")
            print("")
            print('##############################')
            print("")
            print(f'Document located at "{msg}"\nhas now been Encrypted!')
            e.encrypt_file(msg, key)
            print("")
            print('##############################')
            press_continue()
        elif PEIN == 'd2':
            print("Where is the Encrypted Document located?")
            msg = input(" --> ")
            print("")
            print("Where is your key located?")
            key = input(" --> ")
            print("")
            print('##############################')
            print("")
            print(f'Document located at "{msg}"\nhas now been Decrypted!')
            e.decrypt_file(msg, key)
            print("")
            print('##############################')
            press_continue()
        elif PEIN == '3':
            print("Where is the Image located?")
            msg = input(" --> ")
            file_name, file_ext = os.path.splitext(msg)
            print("")
            print("Where is your key located?")
            key = input(" --> ")
            print("")
            print('##############################')
            print("")
            print(f'Image located at "{msg}"\nhas now been Encrypted!')
            e.encrypt_image(msg, file_ext, key)
            print("")
            print('##############################')
            press_continue()
        elif PEIN == 'd3':
            print("Where is the Encrypted Image located?")
            msg = input(" --> ")
            file_name, file_ext = os.path.splitext(msg)
            print("")
            print("Where is your key located?")
            key = input(" --> ")
            print("")
            print('##############################')
            print("")
            print(f'Image located at "{msg}"\nhas now been Decrypted!')
            e.decrypt_image(file_name, '.png', key)
            print("")
            print('##############################')
            press_continue()
        elif PEIN == '4':
            print("Where is the Folder located?")
            msg = input(" --> ")
            print("")
            print("Where is your key located?")
            key = input(" --> ")
            print("")
            print('##############################')
            print("")
            e.encrypt_folder(msg, key)
            print("")
            print('##############################')
            press_continue()
        elif PEIN == 'd4':
            print("Where is the Encrypted Folder located?")
            msg = input(" --> ")
            print("")
            print("Where is your key located?")
            key = input(" --> ")
            print("")
            print('##############################')
            print("")
            e.decrypt_folder(msg, key)
            print("")
            print('##############################')
            press_continue()
        elif PEIN == '0':
            print("Where do you want your key to be located?")
            msg = input(" --> ")
            print("What should the name be on your key?")
            name = input(" --> ")
            print('##############################')
            print("")
            print(f'Your key has been generated at:\n{msg}{name}.key')
            e.generate_key(f'{msg}{name}')
            print("")
            print('##############################')
            press_continue()

main_functions()